bind = SUPER, Return, exec, uwsm app -- ghostty
bind = SUPER, B, exec, uwsm app -- flatpak run com.google.Chrome
bind = SUPER CTRL, B, exec, uwsm app -- flatpak run com.google.Chrome --incognito
bind = SUPER, V, exec, uwsm app -- code
bind = SUPER, F, exec, uwsm app -- nautilus --new-window
bind = SUPER, M, exec, uwsm app -- flatpak run org.signal.Signal
bind = SUPER, K, exec, uwsm app -- flatpak run org.gnome.Calculator
bind = SUPER, T, exec, uwsm app -- flatpak run org.gnome.TextEditor
bind = SUPER, SEMICOLON, exec, uwsm app -- flatpak run it.mijorus.smile
#bind = SUPER, A, exec, uwsm app -- $(astal launcher)
bind = SUPER, A, exec, dms ipc call spotlight toggle
bind = SUPER, SPACE, exec, dms ipc call spotlight toggle
bind = SUPER CTRL, L, exec, uwsm app -- hyprlock

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

bind = SUPER ALT, left, movegroupwindow, b
bind = SUPER ALT, right, movegroupwindow, f
bind = SUPER ALT, up, movewindoworgroup, u
bind = SUPER ALT, down, movewindoworgroup, d

bind = SUPER, slash, togglegroup
bind = SUPER, TAB, layoutmsg, swapwithmaster
bind = SUPER SHIFT, TAB, swapactiveworkspaces, HDMI-A-4 eDP-1

bind = SUPER, X, killactive
#bind = SUPER CTRL, F11, fullscreen, 1
bind = , F11, fullscreen, 0

bind = SUPER CTRL, left, exec, hyprnome -p
bind = SUPER CTRL, right, exec, hyprnome
bind = SUPER CTRL SHIFT, left, exec, hyprnome -p -m
bind = SUPER CTRL SHIFT, right, exec, hyprnome -m

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

bind = , PRINT, exec, hyprshot -m region
bind = SUPER, PRINT, exec, hyprshot-no-cursor -m window -m active
bind = SUPER CTRL, PRINT, exec, hyprshot-no-cursor -m output -m active

bind = SUPER CTRL, ESCAPE, exec, systemctl poweroff
bind = SUPER CTRL, R, exec, systemctl reboot
bind = SUPER ALT, R, exec, uwsm stop
bind = SUPER CTRL, S, exec, uwsm app -- hyprpanel toggleWindow settings-dialog

bindc = SUPER, mouse:272, togglefloating

bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl = SUPER, F9, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = SUPER ALT, F9, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bindle = , XF86AudioLowerVolume, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 5%-
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 5%+
bindle = SUPER, F10, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 5%-
bindle = SUPER, F11, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 5%+
bindle = SUPER CTRL, F10, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 1%-
bindle = SUPER CTRL, F11, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SINK@ 1%+

bindle = SUPER ALT, F10, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SOURCE@ 1%-
bindle = SUPER ALT, F11, exec, wpctl set-volume -l '1.0' @DEFAULT_AUDIO_SOURCE@ 1%+

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
