general {
  border_size = 2
  col.active_border = rgb(7199ee)
  col.inactive_border = rgb(374059)
  gaps_in = 6
  gaps_out = 12
  layout = master
  resize_on_border = true

  snap {
    enabled = true
  }
}

ecosystem {
  no_update_news = true
}

master {
  mfact = 0.67
}

input {
  kb_layout = pl
}

cursor {
  default_monitor = HDMI-A-4
  #no_hardware_cursors = 1
}

decoration {
  dim_inactive = true
  dim_strength = 0.3
  rounding = 12

  shadow {
    color = rgba(17172699)
  }
}

group {
  auto_group = true
  insert_after_current = false
  col.border_active = rgb(7199ee)
  col.border_inactive = rgb(374059)
  col.border_locked_active = rgb(9fbbf3)

  groupbar {
    font_size = 12
    font_weight_active = bold
    height = 16
    indicator_height = 3
    gaps_in = 3
    gaps_out = 3
    keep_upper_gap = false
    text_color = rgb(a0a8cd)
    col.active = rgb(7199ee)
    col.inactive = rgb(374059)
  }
}

misc {
  animate_manual_resizes = true
  background_color = rgb(171726)
  disable_hyprland_logo = true
  disable_splash_rendering = true
  force_default_wallpaper = 2
  font_family = FiraCode Nerd Font
  vrr = 1
}

binds {
  movefocus_cycles_groupfirst = true
  drag_threshold = 10
}
