exec-once = uwsm app -- hyprlock --immediate

#exec-once = hyprpanel
#exec-once = astal-shell
exec-once = dbus-update-activation-environment --systemd --all
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = wl-clip-persist --clipboard regular

exec-once = uwsm app -- flatpak run org.signal.Signal --start-in-tray

# Chrome fullscreen bugfix
exec-once = fullscreen-fix