exec-once = uwsm app -- hyprlock --immediate

exec-once = astal-shell
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = wl-clip-persist --clipboard regular

# Chrome fullscreen bugfix
exec-once = fullscreen-fix