#wallpaper {
#  path = ~/Pictures/Wallpapers/wp8787151-anime-4k-scenery-wallpapers.jpg
#}

preload = ~/Pictures/Wallpapers/wp8787151-anime-4k-scenery-wallpapers.jpg
wallpaper = ,~/Pictures/Wallpapers/wp8787151-anime-4k-scenery-wallpapers.jpg
splash = false