general {
  lock_cmd = pidof hyprlock || hyprlock --grace 10
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 1200  # 20min
  on-timeout = loginctl lock-session
}

listener {
  timeout = 1230  # 20.5min
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 5400  # 1.5h
  on-timeout = systemctl suspend
  on-resume = hyprctl reload && hyprctl reload
}
