$font = FiraCode Nerd Font
$text_color = rgb(a0a8cd)
$input_fg = rgb(a0a8cd)
$input_bg = rgba(37405980)

$check_color = rgb(7199ee)
$fail_color = rgb(ee6d85)

$avatar = ~/.config/avatar.jpg
$monitor = HDMI-A-4

# GENERAL
general {
  #hide_cursor = true
  grace = 0
}

# BACKGROUND
background {
  monitor =
  path = screenshot
  color = rgb(22273d)
  blur_passes = 3
}

# Profie-Photo
image {
  monitor = $monitor
  path = $avatar
  border_size = 6
  border_color = $input_bg
  size = 130
  rounding = -1
  rotate = 0
  reload_time = -1
  reload_cmd = 
  position = 0, -80
  halign = center
  valign = center
}

# Day-Month-Date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
  color = $text_color
  font_size = 25
  font_family = $font
  position = 0, -160
  halign = center
  valign = top
}

# Time
label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
  color = $text_color
  font_size = 120
  font_family = $font
  position = 0, -200
  halign = center
  valign = top
}

# USER-BOX
shape {
  monitor = $monitor
  size = 300, 60
  color = $input_bg
  rounding = -1

  position = 0, 232
  halign = center
  valign = bottom
}

# USER
label {
  monitor = $monitor
  text = $USER
  color = $input_fg
  font_size = 18
  font_family = $font
  position = 0, 247
  halign = center
  valign = bottom
}

# USER ICON
label {
  monitor = $monitor
  text =   
  color = $input_fg
  font_size = 18
  font_family = $font
  position = -125, 247
  halign = center
  valign = bottom
}

# PASSWORD FIELD
input-field {
  monitor = $monitor
  size = 300, 60
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.25
  dots_center = true
  inner_color = $input_bg
  font_color = $input_fg
  fade_on_empty = false
  font_family = $font
  placeholder_text = password
  check_color = $check_color
  fail_color = $fail_color
  capslock_color = $fail_color
  position = 0, 160
  halign = center
  valign = bottom
}

# PASSWORD ICON
label {
  monitor = $monitor
  text =   
  color = $input_fg
  font_size = 18
  font_family = $font
  position = -125, 175
  halign = center
  valign = bottom
}
