monitorv2 {
  output = HDMI-A-4
#  mode = 1920x1080@60
  mode = 3840x2160@60
  position = auto-left
  scale = 2
#  bitdepth = 10
#  cm = wide
}

monitorv2 {
  output = eDP-1
  mode = 1920x1080@60
  position = auto-right
}

monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@60
  position = auto-right
  disabled = true
}

monitorv2 {
  output = HEADLESS
  mode = 1920x1080@60
  position = auto-right
}

workspace = 1, monitor:HDMI-A-4, default:true
workspace = 2, monitor:eDP-1, default:true
