# Fullscreen border
windowrule = bordercolor rgb(f6955b), fullscreen:1

# Signal
windowrule = float, class:org.signal.Signal
windowrule = persistentsize, class:org.signal.Signal

# OBS
windowrule = float, class:com.obsproject.Studio
windowrule = persistentsize, class:com.obsproject.Studio

# Smile
windowrule = float, class:it.mijorus.smile
windowrule = float, title:wl-clipboard

# File Picker
windowrule = float, class:xdg-desktop-portal-gtk

# GIMP
windowrule = float, class:(file-)(.*), title:(Export Image as )(.*)

# Astal Shell
layerrule = blur, gtk-layer-shell
layerrule = ignorezero, gtk-layer-shell