# See https://sw.kovidgoyal.net/kitty/conf.html
font_family FiraCode Nerd Font
font_size 12

# Shell integration is sourced and configured manually
shell_integration no-rc

confirm_os_window_close -1
show_hyperlink_targets yes
mouse_hide_wait 0
resize_debounce_time 0.01

underline_hyperlinks always

url_style straight
default_pointer_shape arrow
pointer_shape_when_dragging arrow
background_opacity 0.8

clear_all_shortcuts yes

# copy/paste
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

# scroll
map ctrl+page_up scroll_page_up
map ctrl+page_down scroll_page_down
map ctrl+home scroll_home
map ctrl+end scroll_end

# scroll to prompt
map ctrl+shift+up scroll_to_prompt -1
map ctrl+shift+down scroll_to_prompt 1

# Show output of the last command in pager
map alt+g show_last_command_output

include ~/.config/kitty/theme.conf
