packages:
  - glibc-all-langpacks

files:
  "/etc/hostname":
    content: "azari"
  "/etc/locale.conf":
    content: |
      LANG="en_US.utf-8"
  "/etc/vconsole.conf":
    content: |
      KEYMAP=pl2
      FONT=eurlatgr
      XKBLAYOUT=pl,us
      XKBVARIANT=,
  "/etc/X11/xorg.conf/00-keyboard.conf":
    content: |
      Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "pl,us"
        Option "XkbVariant" ","
      EndSection

symlinks:
  "/etc/localtime": "/usr/share/zoneinfo/Europe/Warsaw"
  "/etc/NetworkManager/system-connections": "/var/preserve/NetworkManager/system-connections"